# Generated by Django 6.0 on 2025-12-07 13:31

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='The expense amount (must be positive)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('category', models.CharField(choices=[('FOOD', 'Food & Dining'), ('TRANSPORT', 'Transportation'), ('SHOPPING', 'Shopping'), ('BILLS', 'Bills & Utilities'), ('ENTERTAINMENT', 'Entertainment'), ('HEALTHCARE', 'Healthcare'), ('EDUCATION', 'Education'), ('OTHER', 'Other')], db_index=True, default='OTHER', help_text='The category of the expense', max_length=50)),
                ('date', models.DateField(db_index=True, default=django.utils.timezone.now, help_text='The date when the expense occurred')),
                ('description', models.TextField(blank=True, help_text='Optional description or notes about the expense', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this expense record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this expense record was last updated')),
                ('user', models.ForeignKey(help_text='The user who created this expense', on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Expense',
                'verbose_name_plural': 'Expenses',
                'db_table': 'expenses_expense',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['-date', '-created_at'], name='expenses_ex_date_840b41_idx'), models.Index(fields=['user', '-date'], name='expenses_ex_user_id_4af51e_idx'), models.Index(fields=['user', 'category'], name='expenses_ex_user_id_207090_idx')],
            },
        ),
    ]
